name = "inpi-pi-game"
main = "pi-game-worker.js"
compatibility_date = "2025-08-01"

routes = [
  { pattern = "api.inpinity.online/game*", zone_name = "inpinity.online" }
]

[[kv_namespaces]]
binding = "GAME"
id = "c5195e8c3a8f441089a54179b83fadd2"

[[kv_namespaces]]
binding = "CLAIMS"
id = "139ec0627b02429db4507c14b5a3a1fd"